import type { Metadata } from "next";
import NextSessionProvider from "@/app/_layoutComponents/sessionProvider";
import "@/Styling/index.scss";
import "@/Styling/Pages/homepage.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{children: React.ReactNode;}>) {
  return (
    <NextSessionProvider>
      <html lang="en">
        <body>
          {props.children}
        </body>
      </html>
    </NextSessionProvider>
  );
}


