import type { Metadata } from "next";
import "../index.css";
import { Suspense } from "react"; // prevents full page going to client-side when using useSearchParams()
import GoogleCaptchaWrapper from "@/app/_layoutComponents/googleCaptchaWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/Favicon/favicon.ico' },
    ]
  }
};

export default function RootLayout(props: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <GoogleCaptchaWrapper>
            {props.children}
          </GoogleCaptchaWrapper>
        </Suspense>
      </body>
    </html>
  );
}


